### ISSUE TITLE
Add function to Civis utils

### ISSUE THREAD

**Issue by tiffanychu90** [CityOfLosAngeles/covid19-indicators#21]
Use Civis robot user to do a scheduled `git add`, `git commit`, `git push` and overwrite files on GitHub. Can be used to overwrite the CSVs or push to GitHub pages.

**Comment by ian-r-rose** [comment]
We can start by adding the upload function to the new civis utils package. The hard coded repo, branch name, token name, etc can all be made parameters of the function.

I *think* by using `fsspec.open` it will automatically work for both local and remote files, but we should verify.

**Comment by tiffanychu90** [comment]
Closing via [this](https://github.com/CityOfLosAngeles/aqueduct/pull/326) and [this](https://github.com/CityOfLosAngeles/aqueduct/pull/327) aqueduct PR
