### ISSUE TITLE
Replace lahub data with S3 Parquet Files

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/covid19-indicators#5]

**Comment by tiffanychu90** [comment]
This [aqueduct PR](https://github.com/CityOfLosAngeles/aqueduct/pull/293) adds a parquet export to the DAG. It will regularly save into the public health S3 bucket. Once we have a more public repo, we can move all the files there.

**Comment by tiffanychu90** [comment]
Have test script that writes to S3 bucket and used Civis scheduler (https://platform.civisanalytics.com/spa/#/scripts/containers/78991273)
